# Используем официальный образ Python в качестве базового
FROM python:3.11-slim

# Устанавливаем рабочую директорию
WORKDIR /bot

# Копируем содержимое текущей директории в контейнер
COPY . /bot

# Устанавливаем необходимые пакеты, указанные в requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Запускаем Telegram-бота
CMD ["python", "main_bot.py"]