services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_container
    command: ["sh", "-c", " sleep 5 && alembic upgrade head && uvicorn main:app --reload --host=0.0.0.0 --port=8000"]
    env_file:
      - .env-docker
    ports:
      - "8000:8000"
  bot:
    build:
      context: .
    command: ["python", "main_bot.py"]
    container_name: bot_container
    env_file:
      - .env-docker
  db:
    image: postgres:15.1-alpine
    container_name: db
    command: -p 5454
    expose:
      - 5454
    env_file:
      - .env-docker