"""initial1

Revision ID: 7a5e06a890dc
Revises: c32626bdb4ce
Create Date: 2024-09-01 17:07:20.121874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a5e06a890dc'
down_revision: Union[str, None] = 'c32626bdb4ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('to_address', sa.String(), nullable=False),
    sa.Column('bank', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('processing_balance', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('referal_balance', sa.Integer(), nullable=False))
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'referal_balance')
    op.drop_column('users', 'processing_balance')
    op.drop_table('application')
    # ### end Alembic commands ###
